### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Keboo** [ChrisStayte/Bachup#15]
Overall, it looks like a very solid app. I like the clean layout and setup that you have done. The code is really clean, well organized, and easy to read. 

A few bits of feedback

- I like the custom window layout you have done. One interaction that did not appear to work was double clicking on the header to toggle the maximize state of the window. 
- On the view models you often follow the pattern of "set the backing field" then "raise the property changed event". Typically you check if the new values is different from the existing field and only raise the event if the new value is different. Because the event can sometime cause many bindings to re-evaluate, you want to make sure you only raise it if needed.
- Typically you don't want to use `File.Exists` prior to calling `File.Delete`. Instead just call `File.Delete`. The reason is because when working with files, you can never be 100% sure that some other external process modifies the file system after you have checked to see if the file exists. From the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.delete) you will notices that it does not do anything if the file does not exist.
- You may consider taking a look at [MVVM Light](http://www.mvvmlight.net/). It has a view model class and a relay command that are really close to drop in replacements for what you have in the app.

**Comment by ChrisStayte** [comment]
Thank you @Keboo . The next Iteration of my app will take your guidance and suggestions into account. If you are able to better clarify your second bullet point I would greatly appreciate it :)

**Comment by Keboo** [comment]
Sure. Take this sample from `BachupItemViewModel.cs`
```cs
private bool _isSaving;
public bool IsSaving
{
    get { return _isSaving; }
    set
    {
        _isSaving = value;
        NotifyPropertyChanged();
    }
}
```

If you were to have code that did the following (assuming it is starting equal to `false`):
```cs
IsSaving = true;
IsSaving = true;
IsSaving = false;
```
It would raise the `PropertyChanged` event 3 times, even though the value only changes twice.

So a better implementation of the property would be:
```cs
private bool _isSaving;
public bool IsSaving
{
    get { return _isSaving; }
    set
    {
        if (_isSaving != value)
        {
          _isSaving = value;
          NotifyPropertyChanged();
        }
    }
}
```
Now it will only raise the `PropertyChanged` event when the value has actually changed. This actually ends up causing a bunch of boiler plate code in your view model. You can actually reduce this setter down to a single method similar to the `MutateVerbose` extension method you have in there. The other option is to put the logic in a common base view model class. You can see some example of setting your view models up like that [in my blog post](https://intellitect.com/getting-started-model-view-viewmodel-mvvm-pattern-using-windows-presentation-framework-wpf/).
